#!/Users/ridleylarsen/.rvm/rubies/ruby-2.3.3/bin/ruby

require 'unirest'
require 'time'

def main()
  api_key = 'CHANGEME'
  time_goal = 8 * 60 * 60  # 8 hours or 28800 seconds.
  now = Time.now
  puts "It is now#{now.strftime("%l:%M %p")}."
  t = Time.new(now.year, now.month, now.day).iso8601
  uri = "https://www.toggl.com/api/v8/time_entries?start_date=#{t}"
  response = Unirest.get uri, auth:{:user=>api_key, :password=>"api_token"},
                              headers:{ "Accept" => "application/json" }
  billable_duration = 0
  nonbillable_duration = 0
  for elt in response.body do
    if elt["duration"] < 0
      if elt["billable"]
        billable_duration += (Time.now.to_i + elt["duration"])
      else
        nonbillable_duration += (Time.now.to_i + elt["duration"])
      end
    else
      if elt["billable"]
        billable_duration += elt["duration"]
      else
        nonbillable_duration += elt["duration"]
      end
    end
  end
  billable_hours = billable_duration / 60 / 60
  billable_minutes = (billable_duration / 60) % 60
  percent_finished = (billable_duration / time_goal) * 100
  hours_remaining = (time_goal - billable_duration) / 60 / 60
  minutes_remaining = (time_goal - billable_duration) / 60 % 60
  finished_at = Time.at now.to_i + (time_goal - billable_duration)
  puts "You have logged %d hours and %d minutes and have %d hours and %d minutes left." % [billable_hours, billable_minutes, hours_remaining, minutes_remaining]
  puts "You are %0.2f%% finished with work today." % [percent_finished]
  puts "You will be finished at%s." % [finished_at.strftime("%l:%M %p")]
end

main
